development:
  host: 127.0.0.1
  port: 27017
  database: thegame_development

test:
  host: 127.0.0.1
  port: 27017
  database: thegame_test

# set these environment variables on your prod server
production:
  uri: <%= ENV['MONGOHQ_URL'] %>
